name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  all-linux:
    name: Linux - PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: 
          - 8.1.26
          - 8.2.13
          - 8.3.0

    uses: ./.github/workflows/main-php-matrix.yml
    with:
      php: ${{ matrix.php }}
    secrets: inherit

  all-windows:
    name: Windows - PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.1
            vs-crt: vs16
          - php: 8.2
            vs-crt: vs16
          - php: 8.3
            vs-crt: vs16

    uses: ./.github/workflows/main-php-matrix-windows.yml
    with:
      php: ${{ matrix.php }}
      vs-crt: ${{ matrix.vs-crt }}
    secrets: inherit
